quarkus.application.name=producer-service

kafka.bootstrap.servers=kafka.kafka-demo.svc.cluster.local:9092

mp.messaging.outgoing.davalar.connector=smallrye-kafka
mp.messaging.outgoing.davalar.topic=davalar
mp.messaging.outgoing.davalar.value.serializer=org.apache.kafka.common.serialization.StringSerializer
